version: "3"

services:
  vpn:
    container_name: vpn
    image: ghcr.io/phpdocdev/vpn:latest
    volumes:
      - ./data/vpn/conf:/etc/openvpn
      - ./data/vpn:/host:delegated
    networks:
      - lde-network
    cap_add:
      - NET_ADMIN
    depends_on:
      - "bind"
    ports:
      - "1194:1194/udp"
      - "13194:13194"
    environment:
      DEST: docdev.ovpn
      DEBUG_ENTRYPOINT: 2