version: "3.9"

services:

  # Apache ---------------------------------------------------
  apache:
    container_name: apache
    hostname: apache
    restart: ${DOCKER_RESTART}
    image: ghcr.io/phpdocdev/apache:latest
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: apache
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTP_SSL_PORT:-443}:443"
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
      - ./data/cert:/etc/ssl/certs
    env_file:
      - .env
    networks:
      lde-network:
    dns:
      - ${BIND_IP:-192.168.103.100}

  # PHP ---------------------------------------------------
  php-fpm:
    container_name: php${PHPV}
    hostname: php
    image: ghcr.io/phpdocdev/php:${PHPV}
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: php-fpm
    ports:
      - "9000:9000"
      - "3000:3000"
      - "3001:3001"
      - "${MONIT_PORT:-2849}:2849"
    restart: ${DOCKER_RESTART}
    tmpfs: /var/cache
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
      - ~/.composer/pcomposer:/var/www/.composer/pcomposer:default
      - ./data/cert:/etc/ssl/cert:delegated
      - ./data/.zsh_history:/home/dev/.zsh_history:delegated
      - ./data/php.ini:/usr/local/etc/php/conf.d/zzb-custom.ini:delegated
    env_file:
      - .env
    networks:
      lde-network:
    user: ${CUSTOM_UID:-1000}:${CUSTOM_GID:-1000}
    dns:
      - ${BIND_IP:-192.168.103.100}

  # BinDNS ---------------------------------------------------
  bind:
    container_name: bind
    hostname: bind
    image: ghcr.io/phpdocdev/bind:latest
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: bind
    restart: ${DOCKER_RESTART}
    ports:
      - "${HOST_PORT_BIND:-53}:53/tcp"
      - "${HOST_PORT_BIND:-53}:53/udp"
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP:-host-gateway}"
    environment:
      - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT}
      - DNS_A=${TLD_SUFFIX:-*.loc}=${TLD_HOST:-apache},*.host=host.docker.internal,mysql=${MYSQL_HOST:-host.docker.internal},redis=${REDIS_HOST:-host.docker.internal},${EXTRA_HOSTS}
      - DNSSEC_VALIDATE=${BIND_DNSSEC_VALIDATE:-no}
      - DOCKER_LOGS=${BIND_LOG_DNS_QUERIES-1}
      - DNS_FORWARDER=${DNS_FORWARDERS}
      - ALLOW_RECURSION=any
    dns:
      - 127.0.0.1
    networks:
      lde-network:
        ipv4_address: ${BIND_IP:-192.168.103.100}

  # MailHog ---------------------------------------------------
  mailhog:
    container_name: mailhog
    hostname: mailhog
    restart: ${DOCKER_RESTART}
    image: ghcr.io/phpdocdev/mailhog:latest
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: mailhog
    ports:
      - "${MAILHOG_PORT:-8025}:8025"
    networks:
      lde-network:

networks:
  lde-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      dns: ${DNS}
      dns_search: bind
    ipam:
      driver: default
      config:
        - subnet: 192.168.103.0/24
          gateway: 192.168.103.1