version: '3'

networks:
  lde-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.103.0/24
          gateway: 192.168.103.1
volumes:
  cert:

services:
  # Apache ---------------------------------------------------
  apache:
    container_name: apache
    hostname: apache
    restart: ${DOCKER_RESTART}
    image: brandonkiefer/php-dev:apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
      - ./cert:/etc/ssl/certs
    env_file:
      - .env
    networks:
      lde-network:
        ipv4_address: 192.168.103.100
    dns:
      - 192.168.103.106

  # PHP 8.0 ---------------------------------------------------
  php-fpm:
    container_name: php${PHPV}
    hostname: php
    build:
      context: ./php
      dockerfile: ./${PHPV}/Dockerfile
      args:
        - CUSTOM_USER_NAME=${CUSTOM_USER_NAME}
        - CUSTOM_UID=${CUSTOM_UID}
        - CUSTOM_GID=${CUSTOM_GID}
        - PHPV=${PHPV}
    ports:
      - "9000:9000"
      - "3000:3000" # Browser Sync
      - "3001:3001" # Browser Sync UI
    extra_hosts:
      - "mysql:${DOCKER_HOST_IP}"
      - "redis:${DOCKER_HOST_IP}"
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
      - ./cert:/etc/ssl/cert
    environment:
      - ENVIRONMENT_NAME=local
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    dns:
      - 192.168.103.106
  bind:
    container_name: bind
    hostname: bind
    image: brandonkiefer/php-dev:bind
    restart: always
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_BIND:-53}:53/tcp"
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_BIND:-53}:53/udp"

    environment:
      - DEBUG_ENTRYPOINT=${DEBUG_COMPOSE_ENTRYPOINT}

      - WILDCARD_DNS=${TLD_SUFFIX:-loc}=${DOCKER_HOST_IP}
      - EXTRA_HOSTS=${EXTRA_HOSTS}

      - DNS_FORWARDER=${BIND_DNS_RESOLVER:-9.9.9.9,8.8.4.4}

      - DNSSEC_VALIDATE=${BIND_DNSSEC_VALIDATE:-no}

      - TTL_TIME=${BIND_TTL_TIME}
      - REFRESH_TIME=${BIND_REFRESH_TIME}
      - RETRY_TIME=${BIND_RETRY_TIME}
      - EXPIRY_TIME=${BIND_EXPIRY_TIME}
      - MAX_CACHE_TIME=${BIND_MAX_CACHE_TIME}

      - DOCKER_LOGS=${BIND_LOG_DNS_QUERIES-1}

    dns:
      - 127.0.0.1
    networks:
      lde-network:
        ipv4_address: 192.168.103.106
  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: brandonkiefer/php-dev:mailhog
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_MAILHOG:-8025}:8025"
    networks:
      lde-network:
        ipv4_address: 192.168.103.108