version: '3.9'

networks:
  lde-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      dns: ${DNS}
    ipam:
      driver: default
      config:
        - subnet: 192.168.103.0/24
          gateway: 192.168.103.1
volumes:
  cert:

services:
  # Apache ---------------------------------------------------
  apache:
    container_name: apache
    hostname: apache
    restart: ${DOCKER_RESTART}
    image: ghcr.io/phpdocdev/apache:latest
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
      - ./data/cert:/etc/ssl/certs
    env_file:
      - .env
    networks:
      lde-network:
        ipv4_address: 192.168.103.100
    dns:
      - 192.168.103.106

  # PHP ---------------------------------------------------
  php-fpm:
    container_name: php${PHPV}
    hostname: php
    image: ghcr.io/phpdocdev/php:${PHPV}
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: php-fpm
    ports:
      - "9000:9000"
      - "3000:3000"
      - "3001:3001"
    extra_hosts:
      - "mysql:${DOCKER_HOST_IP}"
      - "redis:${DOCKER_HOST_IP}"
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
      - ./data/.zsh_history:/home/dev/.zsh_history:delegated
    env_file:
      - .env
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}
    dns: 
      - 192.168.103.106

  # BinDNS ---------------------------------------------------
  bind:
    container_name: bind
    hostname: bind
    image: ghcr.io/phpdocdev/bind:latest
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: bind
    restart: always
    ports:
      - "${HOST_PORT_BIND:-53}:53/tcp"
      - "${HOST_PORT_BIND:-53}:53/udp"
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_IP}"
    environment:
      - DEBUG_ENTRYPOINT=${DEBUG_COMPOSE_ENTRYPOINT}
      - DNS_A=${TLD_SUFFIX:-*.loc}=${TLD_HOST:-apache},*.host=${DOCKER_HOST_IP},mysql=${MYSQL_HOST:-127.0.0.1},redis=${REDIS_HOST:-127.0.0.1},php=php,bind=bind,apache=apache,mailhog=mailhog,${EXTRA_HOSTS}
      - DNSSEC_VALIDATE=${BIND_DNSSEC_VALIDATE:-no}
      - DOCKER_LOGS=${BIND_LOG_DNS_QUERIES-1}
      - ALLOW_RECURSION=any
    dns:
      - 127.0.0.1
    networks:
      lde-network:
        ipv4_address: 192.168.103.106

  # MailHog ---------------------------------------------------
  mailhog:
    container_name: mailhog
    hostname: mailhog
    image: ghcr.io/phpdocdev/mailhog:latest
    extends:
      file: ${COMPOSE_OVERRIDE_FILE}
      service: mailhog
    ports:
      - "${HOST_PORT_MAILHOG:-8025}:8025"
    networks:
      lde-network:
        ipv4_address: 192.168.103.108