version: '3'

services:
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: ${DOCKER_RESTART}
    image: "phpmyadmin"
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=128M
      - MEMORY_LIMIT=512M
      - MAX_EXECUTION_TIME=1000
    links:
      - mysql
    ports:
      - "8080:80"
    networks:
      lde-network:
