version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    restart: ${DOCKER_RESTART}
    image: "redis:6-alpine"
    ports:
      - "6379:6379"
    networks:
      lde-network:
